#!/bin/bash


export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
rm app/build -fr
#./gradlew assembleDebug -DskipFormatKtlint 
./gradlew assembleRelease -DskipFormatKtlint  --parallel 
exit 0

~/android/build-tools/34.0.0/apksigner sign --ks-key-alias alias_name  --ks \
  ~/android/p/PipePipe/PipePipeClient/my-key.keystore \
app/build/outputs/apk/release/PipePipe_4.8.1-arm64-v8a-release-unsigned.apk

adb install -g app/build/outputs/apk/release/PipePipe_4.8.1-arm64-v8a-release-unsigned.apk

